-- ============================================================================
-- RAJ HANS EVENTS - NEON POSTGRESQL COMPLETE DATABASE SCHEMA
-- Generated directly from your Supabase production database export.
-- Copy and paste this entire file into your Neon SQL Editor and click "Run".
-- ============================================================================

-- 1. About Us
CREATE TABLE IF NOT EXISTS about_us (
  identifier TEXT NOT NULL PRIMARY KEY,
  description TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

-- 2. Contact Information
CREATE TABLE IF NOT EXISTS contact_info (
  identifier TEXT NOT NULL PRIMARY KEY,
  email TEXT,
  phone TEXT,
  location TEXT,
  insta TEXT,
  fb TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

-- 3. Experiences (Video Stories)
CREATE TABLE IF NOT EXISTS experiences (
  identifier TEXT NOT NULL PRIMARY KEY,
  title TEXT,
  video_url TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_experiences_created ON experiences(created_at);

-- 4. Our Expertise
CREATE TABLE IF NOT EXISTS expertise (
  identifier TEXT NOT NULL PRIMARY KEY,
  title TEXT,
  image_url TEXT,
  thumbnail_url TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_expertise_created ON expertise(created_at);

-- 5. Featured Moments
CREATE TABLE IF NOT EXISTS featured (
  identifier TEXT NOT NULL PRIMARY KEY,
  title TEXT,
  image_url TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_featured_created ON featured(created_at);

-- 6. Home Content
CREATE TABLE IF NOT EXISTS home_content (
  identifier TEXT NOT NULL PRIMARY KEY,
  logo_url TEXT,
  banner_video_url TEXT,
  banner_title TEXT,
  banner_text TEXT,
  founded TEXT,
  thumbnail_url TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

-- 7. Packages
CREATE TABLE IF NOT EXISTS packages (
  identifier TEXT NOT NULL PRIMARY KEY,
  pkg_name TEXT,
  f1 TEXT,
  f2 TEXT,
  f3 TEXT,
  f4 TEXT,
  price TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_packages_created ON packages(created_at);

-- 8. Portfolio (Includes auto-incrementing ID & unique identifier)
CREATE TABLE IF NOT EXISTS portfolio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  identifier TEXT NOT NULL UNIQUE,
  title TEXT,
  category TEXT,
  media_type TEXT,
  media_url TEXT,
  thumbnail_url TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_portfolio_created ON portfolio(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_portfolio_category ON portfolio(category);

-- 9. Profiles (Admin / User Roles)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT,
  role TEXT DEFAULT 'user',
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

-- 10. Services
CREATE TABLE IF NOT EXISTS services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  identifier TEXT NOT NULL UNIQUE,
  title TEXT,
  tag TEXT,
  "desc" TEXT,
  image_url TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_services_created ON services(created_at);

-- 11. Smiles (Celebration Moments)
CREATE TABLE IF NOT EXISTS smiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  identifier TEXT NOT NULL UNIQUE,
  image_url TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_smiles_created ON smiles(created_at);

-- 12. Team
CREATE TABLE IF NOT EXISTS team (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  identifier TEXT NOT NULL UNIQUE,
  name TEXT,
  role TEXT,
  photo_url TEXT,
  thumbnail_url TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_team_created ON team(created_at);

-- 13. Testimonials
CREATE TABLE IF NOT EXISTS testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  identifier TEXT NOT NULL UNIQUE,
  name TEXT,
  comment TEXT,
  stars INTEGER,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_testimonials_created ON testimonials(created_at);

-- 14. Client Enquiries (Website Inquiries & Contact Submissions)
CREATE TABLE IF NOT EXISTS enquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  event_type TEXT,
  event_date TEXT,
  guests TEXT,
  budget TEXT,
  message TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_enquiries_created ON enquiries(created_at DESC);
